### ISSUE TITLE
Is it possible to add overlay icon for small taskbar buttons? 

### ISSUE THREAD

**Issue by modulexcite** [ashmind/SolutionIcon#2]
Thank you for the extension.
Is it possible to display the overlay icon when I have the setting "Use small icons" turned on?

**Comment by ashmind** [comment]
@modulexcite Forgot to update you, but I did some research and unfortunately Windows does not seems to support overlay in that mode. It might be still possible to manually paint over the icon -- but I don't think I'll have time to look into it.

**Comment by modulexcite** [comment]
thanks for the update and the extension. I'll take a stab at it and if I'm able to solve it, I'll create a pull request.
